### ISSUE TITLE
How did you get the data? 

### ISSUE THREAD

**Issue by nathanramoscfa** [amanbthakkar/crypto_finance#1]
For the stock-to-flow model notebook, how did you get the data? 

```
# obtain block headers and extract time and height
df = pd.read_csv("____.csv")[["time","height"]]
df["time"] = pd.to_datetime(df["time"], unit="s") #time in seconds
```

The above code returns a `FileNotFoundError: [Errno 2] No such file or directory: '____.csv'`

**Comment by amanbthakkar** [comment]
Hey Nathan, I am away for a few days right now but if you check the comments on the blog post of the corresponding article you should find a link in one of my responses. Let me know if you have further questions!
